"""Tests for confidence/provenance propagation into the Knowledge Graph.

The KnowledgeNode/KnowledgeEdge schema (velune/knowledge/schemas.py) and
storage (velune/knowledge/graph.py) gained confidence/provenance columns —
this verifies KnowledgeGraphPatcher actually populates them from real
signals rather than leaving every node/edge at the default 1.0/[]:

- A dynamic-import edge (parser._extract_dynamic_imports) carries its
  resolution confidence through into KnowledgeEdge.confidence/provenance,
  not just .weight.
- A symbol from the universal fallback extractor (no dedicated AST/tree-
  sitter/regex pattern set for its language) is scored lower than a
  grammar-verified one.

Also covers a genuine pre-existing bug this work surfaced: an ordinary
`import os` statement crashed KnowledgeGraphPatcher with a foreign-key
IntegrityError, because `f"file:{repo_edge.target}"` (e.g. "file:os") was
never a real node — the patcher parses one file at a time and, unlike
RepositoryGrapher (which gets the whole repo's file list precisely to
resolve import targets), had no way to know whether a target was real.
`KnowledgeGraphPatcher._drop_edges_to_unknown_targets` (using the new
`KnowledgeGraph.existing_node_ids`) fixes this by dropping an edge to an
unresolvable target instead of inserting a broken reference.
"""

from __future__ import annotations

import asyncio

from velune.intelligence.graph_patcher import KnowledgeGraphPatcher
from velune.knowledge.graph import KnowledgeGraph
from velune.knowledge.schemas import EdgeType
from velune.repository.incremental_indexer import IndexDelta


async def _patch(root, delta):
    graph = KnowledgeGraph(root / ".velune" / "kg.db")
    await graph.initialize()
    patcher = KnowledgeGraphPatcher(graph, root)
    result = await patcher.patch(delta)
    return graph, result


# ── Regression: ordinary static imports no longer crash the patcher ───────


def test_ordinary_stdlib_import_does_not_raise_fk_violation(tmp_path):
    (tmp_path / "x.py").write_text(
        "import os\n\n\ndef f():\n    return os.getcwd()\n", encoding="utf-8"
    )

    async def run():
        return await _patch(tmp_path, IndexDelta(to_add=["x.py"]))

    graph, result = asyncio.run(run())
    assert result.errors == 0
    assert result.files_patched == 1


# ── _parse_file confidence assignment (unit-level, no DB/FK involved) ─────


def test_parse_file_fully_literal_dynamic_import_is_full_confidence(tmp_path):
    """importlib.import_module("os") — a plain string literal, no f-string
    interpolation — is exactly as resolvable as a static import (see
    RepositorySnapshotParser._classify_dynamic_import_arg): is_dynamic=False,
    confidence=1.0."""
    (tmp_path / "loader.py").write_text(
        'import importlib\n\nimportlib.import_module("os")\n', encoding="utf-8"
    )
    patcher = KnowledgeGraphPatcher(graph=None, workspace_root=tmp_path)
    _, edges = patcher._parse_file("loader.py")

    import_edges = [e for e in edges if e.edge_type == EdgeType.IMPORTS]
    resolved = [e for e in import_edges if e.provenance == ["imports"]]
    assert resolved
    assert all(e.confidence == 1.0 for e in resolved)


def test_parse_file_partial_prefix_dynamic_import_is_lower_confidence(tmp_path):
    """importlib.import_module(f"plugins.{name}") only has a partial
    literal prefix — lower confidence, tagged imports_dynamic in
    provenance so a caller can tell it apart from a fully-resolved
    import."""
    (tmp_path / "loader.py").write_text(
        "import importlib\n\n\ndef load(name):\n"
        '    importlib.import_module(f"plugins.{name}")\n',
        encoding="utf-8",
    )
    patcher = KnowledgeGraphPatcher(graph=None, workspace_root=tmp_path)
    _, edges = patcher._parse_file("loader.py")

    dynamic_edges = [e for e in edges if e.provenance == ["imports_dynamic"]]
    assert dynamic_edges
    assert all(e.confidence < 1.0 for e in dynamic_edges)


def test_parse_file_opaque_and_generated_nodes_are_lower_confidence(tmp_path):
    (tmp_path / "gen.py").write_text(
        "# Code generated by protoc-gen-go. DO NOT EDIT.\ndef f():\n    pass\n",
        encoding="utf-8",
    )
    patcher = KnowledgeGraphPatcher(graph=None, workspace_root=tmp_path)
    nodes, _ = patcher._parse_file("gen.py")

    assert len(nodes) == 1
    assert nodes[0].confidence < 1.0
    assert nodes[0].provenance == ["generated_marker"]


# ── Unresolved dynamic-import prefixes are dropped, not fabricated ────────


def test_unresolved_dynamic_prefix_is_dropped_not_fabricated(tmp_path):
    """RepositoryGrapher expands a partial prefix against the *whole*
    repo's file list (see _add_dynamic_prefix_edges) — but
    KnowledgeGraphPatcher parses one file at a time with no such list, so
    it correctly can't resolve "plugins" to a real node and must drop the
    edge rather than insert a broken reference."""
    (tmp_path / "loader.py").write_text(
        "import importlib\n\n\ndef load(name):\n"
        '    importlib.import_module(f"plugins.{name}")\n',
        encoding="utf-8",
    )
    (tmp_path / "plugins").mkdir()
    (tmp_path / "plugins" / "__init__.py").write_text("", encoding="utf-8")
    (tmp_path / "plugins" / "plugin_a.py").write_text("def run():\n    return 1\n", encoding="utf-8")

    async def run():
        graph, result = await _patch(
            tmp_path, IndexDelta(to_add=["loader.py", "plugins/__init__.py", "plugins/plugin_a.py"])
        )
        neighbor_results = await graph.neighbors("file:loader.py")
        loader_symbols = await graph.get_nodes_by_file("loader.py")
        return result, neighbor_results, loader_symbols

    result, neighbor_results, loader_symbols = asyncio.run(run())
    assert result.errors == 0  # dropped cleanly, not a parse/patch failure
    assert not any(e.provenance == ["imports_dynamic"] for _, e in neighbor_results)

    # The dynamic-loading behavior is still recorded as a symbol (name is
    # the resolved prefix "plugins", provenance/confidence mark it as a
    # dynamic-import claim), even though no edge could be resolved — same
    # "absent edge beats a wrong one, but still record that something
    # dynamic happened" principle as the parser layer.
    plugins_node = next(s for s in loader_symbols if s.label == "plugins")
    assert plugins_node.provenance == ["dynamic_import"]
    assert plugins_node.confidence < 1.0


# ── Generic-fallback symbols are scored lower than a structural parse ─────


def test_generic_fallback_symbol_scored_lower_than_structural_parse(tmp_path):
    """Lua has no dedicated pattern set — its symbols come from
    _GENERIC_FALLBACK_PATTERNS and should be less confident than a real
    Python file's grammar-verified symbols."""
    (tmp_path / "script.lua").write_text("function greet()\n  return 1\nend\n", encoding="utf-8")
    (tmp_path / "real.py").write_text("def greet():\n    return 1\n", encoding="utf-8")

    async def run():
        graph, _ = await _patch(tmp_path, IndexDelta(to_add=["script.lua", "real.py"]))
        lua_symbols = await graph.get_nodes_by_file("script.lua")
        py_symbols = await graph.get_nodes_by_file("real.py")
        return lua_symbols, py_symbols

    lua_symbols, py_symbols = asyncio.run(run())

    lua_func = next(s for s in lua_symbols if s.label == "greet")
    py_func = next(s for s in py_symbols if s.label == "greet")

    assert lua_func.confidence < 1.0
    assert lua_func.provenance == ["generic_fallback_regex"]
    assert py_func.confidence == 1.0
    assert py_func.provenance == ["structural_parse"]
