"""Regression tests for vendor-directory and generated-file-marker exclusion.

``docs/REPOSITORY_INTELLIGENCE_BASELINE.md`` Recommendation 2: recognize
``vendor/``, ``third_party/``, and generated-code markers as a discovery-time
exclusion class, consistent with the existing ``node_modules``/``dist``
treatment. Two distinct mechanisms implement this:

- Directory name (``vendor/``, ``third_party/``, ...) → excluded from
  discovery entirely (``scanner.py``'s hardcoded skip patterns), the same
  as ``node_modules/``: never even counted.
- A generated-file marker (``@generated``, ``DO NOT EDIT``, ...) in a file's
  leading content → the file is still discovered and recorded, but treated
  as opaque (no structural parse), since the marker can appear anywhere,
  independent of directory name.
"""

from __future__ import annotations

import asyncio

from velune.intelligence.graph_patcher import KnowledgeGraphPatcher
from velune.knowledge.graph import KnowledgeGraph
from velune.repository.incremental_indexer import IncrementalIndexer, IndexDelta
from velune.repository.indexer import RepositoryIndexer
from velune.repository.scanner import FilesystemScanner


def test_vendor_directory_excluded_from_discovery(tmp_path):
    (tmp_path / "vendor" / "dep.py").parent.mkdir(parents=True, exist_ok=True)
    (tmp_path / "vendor" / "dep.py").write_text("def f():\n    pass\n", encoding="utf-8")
    (tmp_path / "third_party" / "lib.py").parent.mkdir(parents=True, exist_ok=True)
    (tmp_path / "third_party" / "lib.py").write_text("def g():\n    pass\n", encoding="utf-8")
    (tmp_path / "real.py").write_text("def h():\n    pass\n", encoding="utf-8")

    discovered = {str(p.relative_to(tmp_path)).replace("\\", "/") for p in FilesystemScanner(tmp_path).scan_code_files()}

    assert "real.py" in discovered
    assert not any(p.startswith("vendor/") for p in discovered)
    assert not any(p.startswith("third_party/") for p in discovered)


GENERATED_SOURCE = (
    "# Code generated by protoc-gen-go. DO NOT EDIT.\n"
    "def handler():\n    return 1\n"
)


def test_repository_indexer_treats_generated_marker_as_opaque(tmp_path):
    (tmp_path / "gen.py").write_text(GENERATED_SOURCE, encoding="utf-8")
    (tmp_path / "real.py").write_text("def real():\n    return 2\n", encoding="utf-8")

    snapshot = RepositoryIndexer(tmp_path).index(force=True)

    gen = next(f for f in snapshot.files if f.path == "gen.py")
    real = next(f for f in snapshot.files if f.path == "real.py")

    assert gen.metadata.get("opaque") is True
    assert len(gen.symbols) == 0
    assert len(real.symbols) > 0


def test_incremental_indexer_treats_generated_marker_as_opaque(tmp_path):
    (tmp_path / "gen.py").write_text(GENERATED_SOURCE, encoding="utf-8")
    state_path = tmp_path / ".velune" / "index_state.json"

    async def run():
        return await IncrementalIndexer(tmp_path, state_path).apply_delta(IndexDelta(to_add=["gen.py"]))

    state = asyncio.run(run())
    assert state.file_index["gen.py"].symbol_count == 0


def test_knowledge_graph_patcher_treats_generated_marker_as_opaque(tmp_path):
    (tmp_path / "gen.py").write_text(GENERATED_SOURCE, encoding="utf-8")

    async def run():
        graph = KnowledgeGraph(tmp_path / ".velune" / "kg.db")
        await graph.initialize()
        patcher = KnowledgeGraphPatcher(graph, tmp_path)
        result = await patcher.patch(IndexDelta(to_add=["gen.py"]))
        node = await graph.get_node("file:gen.py")
        return result, node

    result, node = asyncio.run(run())
    assert node is not None
    assert node.metadata.get("generated") is True
    assert result.nodes_added == 1
    assert result.edges_added == 0
    assert node.confidence < 1.0
    assert "generated_marker" in node.provenance
