"""Monthly Subsystem Evolution Timeline reporter.

Queries the ``repository_evolution_timeline`` SQLite table written by
``LineageMemoryTier`` and renders human-readable Markdown engineering
changelogs.  This gives Velune long-term institutional memory: it can
always answer *why* a module was restructured months ago.
"""

from __future__ import annotations

import logging
import time
from typing import Any

logger = logging.getLogger("velune.cognition.evolution")


class EvolutionTimelineReporter:
    """Renders Markdown engineering changelogs from the evolution timeline DB.

    Args:
        lineage_memory: A ``LineageMemoryTier`` instance exposing
            ``get_evolution_timeline(subsystem)`` and optionally
            ``log_monthly_snapshot(...)``.
    """

    def __init__(self, lineage_memory: Any) -> None:
        self.lineage_memory = lineage_memory

    # ─────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────

    def generate_report(self, subsystem: str) -> str:
        """Produce a Markdown changelog for the given subsystem.

        Args:
            subsystem: Subsystem path or keyword (e.g. ``"velune/memory/tiers"``).

        Returns:
            A Markdown-formatted engineering changelog string.  Returns a
            placeholder message when no snapshots exist yet.
        """
        snapshots: list[dict[str, Any]] = self.lineage_memory.get_evolution_timeline(subsystem)

        if not snapshots:
            return (
                f"# Evolution Timeline: `{subsystem}`\n\n"
                "> No architecture snapshots recorded yet for this subsystem.\n"
                "> Snapshots are captured automatically after successful execution passes.\n"
            )

        lines: list[str] = [
            f"# Subsystem Evolution Timeline: `{subsystem}`\n",
            f"**Total Snapshots Recorded**: {len(snapshots)}\n",
            "---\n",
        ]

        # Trend indicators
        if len(snapshots) >= 2:
            oldest = snapshots[-1]
            latest = snapshots[0]
            lcom_delta = latest["lcom_average"] - oldest["lcom_average"]
            coupling_delta = latest["coupling_ratio"] - oldest["coupling_ratio"]
            debt_delta = latest["debt_items_count"] - oldest["debt_items_count"]

            lcom_trend = "📈 Worsening" if lcom_delta > 0.5 else ("📉 Improving" if lcom_delta < -0.5 else "➡️  Stable")
            coupling_trend = "📈 Worsening" if coupling_delta > 0.05 else ("📉 Improving" if coupling_delta < -0.05 else "➡️  Stable")
            debt_trend = "📈 Growing" if debt_delta > 2 else ("📉 Shrinking" if debt_delta < -2 else "➡️  Stable")

            lines += [
                "## Architectural Health Trends\n",
                "| Metric | Oldest Snapshot | Latest Snapshot | Trend |",
                "|--------|----------------|----------------|-------|",
                f"| LCOM Average | {oldest['lcom_average']:.2f} | {latest['lcom_average']:.2f} | {lcom_trend} |",
                f"| Coupling Ratio | {oldest['coupling_ratio']:.3f} | {latest['coupling_ratio']:.3f} | {coupling_trend} |",
                f"| Debt Items | {oldest['debt_items_count']} | {latest['debt_items_count']} | {debt_trend} |",
                "\n---\n",
            ]

        lines.append("## Snapshot History\n")

        for snap in snapshots:
            ts_str = time.strftime(
                "%Y-%m-%d %H:%M UTC",
                time.gmtime(float(snap.get("timestamp", 0))),
            )
            milestone = snap.get("major_milestone") or ""
            rationale = snap.get("rationales_summary", "")

            lcom = snap.get("lcom_average", 0.0)
            coupling = snap.get("coupling_ratio", 0.0)
            debt = snap.get("debt_items_count", 0)

            lines.append(f"### 🗓 {ts_str}")
            if milestone:
                lines.append(f"**Milestone**: {milestone}\n")
            lines.append(
                f"- **LCOM Average**: `{lcom:.2f}` "
                f"(cohesion proxy — lower is better)"
            )
            lines.append(f"- **Coupling Ratio**: `{coupling:.3f}` (target < 0.30)")
            lines.append(f"- **Debt Items**: `{debt}`")
            if rationale:
                lines.append(f"- **Rationale**: {rationale}")
            lines.append("")

        lines.append("---")
        lines.append(
            "_Timeline generated by Velune EvolutionTimelineReporter. "
            "Snapshots are captured after each successful autonomous execution pass._"
        )
        return "\n".join(lines)

    def snapshot_current_health(
        self,
        subsystem: str,
        lcom_average: float,
        coupling_ratio: float,
        debt_items_count: int,
        milestone: str | None = None,
        rationale_summary: str = "",
    ) -> None:
        """Log a new monthly snapshot for a subsystem.

        Args:
            subsystem: Target subsystem path or keyword.
            lcom_average: Average LCOM score across all classes in the subsystem.
            coupling_ratio: Cross-module coupling ratio (0.0 to 1.0).
            debt_items_count: Total active debt items in the ledger for this subsystem.
            milestone: Optional short description of a major event (e.g. ``"Migrated to async queue"``).
            rationale_summary: Longer free-form engineering rationale.
        """
        try:
            self.lineage_memory.log_monthly_snapshot(
                subsystem=subsystem,
                lcom_average=lcom_average,
                coupling_ratio=coupling_ratio,
                debt_items_count=debt_items_count,
                milestone=milestone,
                rationale_summary=rationale_summary,
            )
            logger.info(
                "Evolution snapshot logged for '%s' (LCOM=%.2f, coupling=%.3f, debt=%d).",
                subsystem,
                lcom_average,
                coupling_ratio,
                debt_items_count,
            )
        except Exception as exc:
            logger.error("Failed to log evolution snapshot for '%s': %s", subsystem, exc)
