"""Unit tests for the velune doctor diagnostic command."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typer.testing import CliRunner
import pytest
import typer

from velune.cli.commands.doctor import doctor_cmd

runner = CliRunner()
app = typer.Typer()
app.add_typer(doctor_cmd, name="doctor")


def test_doctor_check_normal():
    """Verify doctor command runs and renders the health check table or exits appropriately."""
    result = runner.invoke(app, ["doctor", "check"])
    assert result.exit_code in (0, 1)
    assert "Velune Environment Check" in result.stdout or "check(s) failed." in result.stdout or "All checks passed" in result.stdout


def test_doctor_check_json():
    """Verify doctor check --json returns valid JSON formatting."""
    result = runner.invoke(app, ["doctor", "check", "--json"])
    assert result.exit_code in (0, 1)
    
    try:
        data = json.loads(result.stdout)
        assert isinstance(data, list)
        assert len(data) > 0
        names = [item["name"] for item in data]
        assert "Python Version" in names
        assert "Core Dependencies" in names
    except json.JSONDecodeError:
        pytest.fail(f"doctor --json output is not valid JSON: {result.stdout}")


def test_doctor_check_fix(tmp_path):
    """Verify doctor check --fix generates config, database, and workspace directory."""
    original_cwd = os.getcwd()
    try:
        os.chdir(str(tmp_path))
        
        # Verify no files exist beforehand
        assert not (tmp_path / ".velune").exists()
        assert not (tmp_path / "velune.toml").exists()
        
        result = runner.invoke(app, ["doctor", "check", "--fix"])
        assert result.exit_code in (0, 1)
        
        # Verify they were successfully generated by --fix
        assert (tmp_path / ".velune").exists()
        assert (tmp_path / "velune.toml").exists()
        assert (tmp_path / ".velune" / "velune_cognitive_core.db").exists()
        
    finally:
        os.chdir(original_cwd)
